/* Generated By:JavaCC: Do not edit this line. IsabellaConstants.java */
package org.hammer.isabella.cc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IsabellaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int LB = 8;
  /** RegularExpression Id. */
  int RB = 9;
  /** RegularExpression Id. */
  int LS = 10;
  /** RegularExpression Id. */
  int RS = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int STAR = 14;
  /** RegularExpression Id. */
  int CONDITION = 15;
  /** RegularExpression Id. */
  int COLUMN = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int SIGN = 19;
  /** RegularExpression Id. */
  int EXPONENT = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 22;
  /** RegularExpression Id. */
  int LITERAL = 23;
  /** RegularExpression Id. */
  int COMMENT = 24;
  /** RegularExpression Id. */
  int ANYTHING = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"select\\\"\"",
    "\"\\\"from\\\"\"",
    "\"\\\"where\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\"\\\"*\\\"\"",
    "\"\\\"condition\\\"\"",
    "\"\\\"column\\\"\"",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "<EXPONENT>",
    "<NUMBER>",
    "<FLOATING_NUMBER>",
    "<LITERAL>",
    "<COMMENT>",
    "<ANYTHING>",
  };

}
